language: python
python:
  - "3.5"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod 755 miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - pip install coverage
  - pip install coveralls
  - pip install numpy
  - pip install scipy 
  - pip install scikit-learn
  - pip install nose
  - python setup.py build_ext --inplace

script: nosetests --with-coverage --cover-package=b4msa

after_success: coveralls || echo "Coveralls upload failed"

notifications:
    email:
      recipients:
        - mario.graff@infotec.mx
        - mgraffg@ieee.org
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always