language: python
python:
  - "3.5"

before_install:
  - pip install coverage
  - pip install coveralls
  - python setup.py build_ext --inplace

script: nosetests --with-coverage --cover-package=b4msa

after_success: coveralls || echo "Coveralls upload failed"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/de5c2b7b6637a600eb8c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always